version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: game-forum-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: game-forum
    volumes:
      - mongodb_data:/data/db
    networks:
      - game-forum-network

  # Optional: MongoDB Express for database management
  mongo-express:
    image: mongo-express:latest
    container_name: game-forum-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - game-forum-network

volumes:
  mongodb_data:

networks:
  game-forum-network:
    driver: bridge
