@echo off
echo Switching to DEVELOPMENT environment...
set NODE_ENV=development
echo Starting Docker MongoDB...
docker-compose up -d
timeout /t 3 /nobreak >nul
echo Starting API in development mode...
npm run dev
